export interface Project {
  id: string;
  title: string;
  year: string;
  category: "design" | "ia" | "web" | "branding" | "editorial" | "poster" | "karcher";
  tags: string[];
  description: string;
  images: string[];
  hasBookAnimation?: boolean;
  longDescription?: string;
  tools?: string[];
  externalUrl?: string;
}

export const projects: Project[] = [
  // ===== 2026 =====
  {
    id: "berbel-tattoo-web",
    title: "Berbel Tattoo Web",
    year: "2026",
    category: "web",
    tags: ["Berbel Tattoo", "Web", "Diseño UI", "Frontend", "Reserva online"],
    description: "Catálogo web para Berbel Tattoo, una campaña de tatuajes limitados con diseños disponibles y opción de reserva.",
    images: [
      "/img/projects/2026-berbel-tattoo-web/berbel-home.png",
      "/img/projects/2026-berbel-tattoo-web/berbel-catalogo.png",
      "/img/projects/2026-berbel-tattoo-web/berbel-funciona.png",
      "/img/projects/2026-berbel-tattoo-web/berbel-admin.png",
    ],
    longDescription: "Diseño y desarrollo web programado desde cero para Berbel Tattoo, un tatuador que lanzó una campaña de piezas limitadas. La web funciona como catálogo digital para consultar los tatuajes disponibles, ver la colección y reservar las piezas antes de que desaparezcan. El proyecto incluye diseño visual, experiencia de usuario, frontend y una estructura pensada para que el cliente pueda presentar la campaña de forma clara, directa y reservable.",
    tools: ["Next.js", "React", "Tailwind CSS", "Diseño UI", "Frontend"],
    externalUrl: "https://berbelseries.vercel.app/",
  },
  {
    id: "karcher-instagram-ai-design",
    title: "Gestión de Instagram · Kärcher España",
    year: "2026",
    category: "design",
    tags: ["Karcher", "Instagram", "Gestión de redes", "Contenido"],
    description: "Gestión del perfil de Instagram de Kärcher España: planificación, contenidos, edición y adaptación de publicaciones y reels.",
    images: [
      "/img/projects/2026-karcher-instagram-management/instagram-profile.png",
      "https://www.instagram.com/reel/DbYF5kUIawl/embed/",
      "/img/projects/2026-karcher-instagram-ai/instagram-ai-01.jpg",
      "/img/projects/2026-karcher-instagram-ai/instagram-ai-02.jpg",
      "/img/projects/2026-karcher-instagram-ai/instagram-ai-03.jpeg",
      "/img/projects/2026-karcher-instagram-ai/instagram-ai-07.png",
      "/img/projects/2026-karcher-instagram-ai/instagram-ai-09.png",
      "/img/projects/2026-karcher-instagram-ai/instagram-ai-11.jpeg",
      "/img/projects/2026-karcher-instagram-ai/instagram-ai-29.png",
      "/img/projects/2026-karcher-instagram-ai/instagram-ai-30.png",
    ],
    longDescription: "Gestión de contenidos para el Instagram de Kärcher España, trabajando la planificación del perfil, el planteamiento de publicaciones, la edición de vídeo, el diseño de piezas y la adaptación de mensajes al formato social. La selección reúne la visión general del canal, un reel reproducible y una muestra cuidada de las publicaciones más representativas.",
    tools: ["Planificación de contenidos", "Edición de vídeo", "Diseño social", "Copywriting", "IA como apoyo"],
    externalUrl: "https://www.instagram.com/reel/DbYF5kUIawl/",
  },
  {
    id: "karcher-kira-b200-magazine",
    title: "Karcher KIRA B 200 Magazine",
    year: "2026",
    category: "editorial",
    tags: ["Karcher", "Revista", "Editorial", "Maquetación"],
    description: "Revista editorial para la exposición del producto KIRA B 200 de Karcher. Diseño, composición y maquetación completa.",
    images: [
      "/img/projects/2026-karcher-kira-b200-magazine/page-01.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-02.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-03.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-04.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-05.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-06.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-07.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-08.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-09.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-10.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-11.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-12.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-13.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-14.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-15.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-16.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-17.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-18.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-19.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-20.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-21.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-22.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-23.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-24.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-25.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-26.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-27.jpg",
      "/img/projects/2026-karcher-kira-b200-magazine/page-28.jpg",
    ],
    hasBookAnimation: true,
    longDescription: "Revista creada para una exposición dedicada al producto KIRA B 200 de Karcher. Me encargué del diseño editorial, la composición visual y la maquetación completa de la pieza, cuidando la jerarquía de información, el ritmo entre páginas y la preparación del documento final para presentación e impresión. En el portfolio se muestra como libro interactivo para poder recorrer la revista página a página.",
    tools: ["InDesign", "Photoshop", "Illustrator"],
  },
  {
    id: "karcher-news-julio",
    title: "Karcher News Julio",
    year: "2026",
    category: "editorial",
    tags: ["Karcher", "Revista", "Retail", "Promociones"],
    description: "Karcher News para Karcher Centers y ferreterías. Diseño editorial, maquetación y preparación para impresión.",
    images: [
      "/img/projects/2026-karcher-news-julio/page-1.jpg",
      "/img/projects/2026-karcher-news-julio/page-2.jpg",
      "/img/projects/2026-karcher-news-julio/page-3.jpg",
      "/img/projects/2026-karcher-news-julio/page-4.jpg",
      "/img/projects/2026-karcher-news-julio/page-5.jpg",
      "/img/projects/2026-karcher-news-julio/page-6.jpg",
      "/img/projects/2026-karcher-news-julio/page-7.jpg",
      "/img/projects/2026-karcher-news-julio/page-8.jpg",
    ],
    hasBookAnimation: true,
    longDescription: "Karcher News es una publicación interna/comercial que se realiza cada tres o cuatro meses con promociones exclusivas para Karcher Centers, ferreterías y puntos de venta. En esta edición me encargué de todo el proceso: diseño, composición, maquetación editorial, organización de promociones y preparación de archivos previos a impresión. En el portfolio se muestra como libro interactivo, con portada independiente y dobles páginas interiores.",
    tools: ["InDesign", "Photoshop", "Illustrator", "Arte final"],
  },
  {
    id: "karcher-expocadena-stand-2026",
    title: "Karcher Expocadena Stand 2026",
    year: "2026",
    category: "design",
    tags: ["Karcher", "Evento", "Stand", "Impresión"],
    description: "Diseños para el stand de Karcher en Expocadena 2026. Gráficas de gran formato, folletos y piezas impresas preparadas para producción.",
    images: [
      "/img/projects/2026-karcher-expocadena-stand/built-for-life-8m.jpg",
      "/img/projects/2026-karcher-expocadena-stand/go-further-6m.jpg",
      "/img/projects/2026-karcher-expocadena-stand/pared-frontal-2x27.jpg",
      "/img/projects/2026-karcher-expocadena-stand/pared-lateral-2x27.jpg",
      "/img/projects/2026-karcher-expocadena-stand/pared-lateral2-2x27.jpg",
      "/img/projects/2026-karcher-expocadena-stand/folleto-hpw-1.jpg",
      "/img/projects/2026-karcher-expocadena-stand/folleto-hpw-2.jpg",
      "/img/projects/2026-karcher-expocadena-stand/tarjeta-participacion-1.jpg",
      "/img/projects/2026-karcher-expocadena-stand/tarjeta-participacion-2.jpg",
    ],
    longDescription: "Proyecto de diseño para el stand de Karcher en Expocadena 2026. Me encargué de preparar las gráficas necesarias para el espacio del evento, incluyendo paredes de gran formato, piezas laterales, visuales de campaña, folleto HPW y tarjeta de participación. El trabajo cubre diseño, composición, adaptación a medidas reales, escalados de producción y preparación de artes finales para impresión.",
    tools: ["Illustrator", "Photoshop", "InDesign", "Arte final"],
  },
  {
    id: "karcher-amazon-banners",
    title: "Karcher Amazon Store Banners",
    year: "2026",
    category: "design",
    tags: ["Karcher", "Amazon", "Banners", "E-commerce"],
    description: "Sistema de banners para la tienda de Amazon de Karcher. Concepto, composición visual y adaptación a distintos formatos comerciales.",
    images: [
      "/img/projects/2026-karcher-amazon-banners/mesa-de-trabajo-2-100.jpg",
      "/img/projects/2026-karcher-amazon-banners/rcw-header-landing.jpg",
      "/img/projects/2026-karcher-amazon-banners/banner-se2-fcv4.jpg",
      "/img/projects/2026-karcher-amazon-banners/home-hpw.jpg",
      "/img/projects/2026-karcher-amazon-banners/banner-home-wd.jpg",
      "/img/projects/2026-karcher-amazon-banners/wd-7-imagen-flat-lay-accesorios.jpg",
      "/img/projects/2026-karcher-amazon-banners/limpia-ventanas-banner-bodegon-categoria-wv.jpg",
      "/img/projects/2026-karcher-amazon-banners/rcw-banner-landing-wv.jpg",
      "/img/projects/2026-karcher-amazon-banners/banner-julio-970x250-05.jpg",
      "/img/projects/2026-karcher-amazon-banners/banner-julio-300x250-02.jpg",
      "/img/projects/2026-karcher-amazon-banners/goldbox-ilm-mobile-100.jpg",
      "/img/projects/2026-karcher-amazon-banners/karcher-fcv4-amazon-26.mp4",
    ],
    longDescription: "Conjunto de banners desarrollados durante 2026 para diferentes necesidades de la tienda de Amazon de Karcher. Me encargué de la idea creativa, la composición, la jerarquía visual y el proceso de producción de piezas adaptadas a formatos promocionales, landings, cabeceras y espacios de categoría. Algunas imágenes se apoyaron en IA para acelerar la generación de recursos y ampliar posibilidades visuales, manteniendo siempre el resultado dentro del lenguaje de marca.",
    tools: ["Photoshop", "Illustrator", "IA generativa"],
  },
  {
    id: "karcher-web-campaigns",
    title: "Karcher Web Campaigns",
    year: "2026",
    category: "design",
    tags: ["Karcher", "Campañas online", "Web", "Promociones"],
    description: "Campañas online para la web de Karcher. Gestión mensual, concepto visual y adaptación de piezas promocionales.",
    images: [
      "/img/projects/2026-karcher-web-campaigns/rebajas-verano-1900x790-01.jpg",
      "/img/projects/2026-karcher-web-campaigns/rebajas-verano-1900x704-11.jpg",
      "/img/projects/2026-karcher-web-campaigns/rebajas-verano-2025x750-07.jpg",
      "/img/projects/2026-karcher-web-campaigns/h-general-yellow-week-1900x790px.gif",
      "/img/projects/2026-karcher-web-campaigns/banners-abril-1900x790-02.jpg",
      "/img/projects/2026-karcher-web-campaigns/promo-cupon-mayo-26-1900x790-01.jpg",
      "/img/projects/2026-karcher-web-campaigns/promo-cupon-mayo-26-1900x790-02.jpg",
      "/img/projects/2026-karcher-web-campaigns/promo-cupon-mayo-26-750x500-08.jpg",
      "/img/projects/2026-karcher-web-campaigns/flash-sin-iva-1900x704-03.jpg",
      "/img/projects/2026-karcher-web-campaigns/flash-sin-iva-1200x1200-04.jpg",
      "/img/projects/2026-karcher-web-campaigns/flash-sin-iva-400x200-09.jpg",
      "/img/projects/2026-karcher-web-campaigns/banner-gama-se-1600x667.jpg",
      "/img/projects/2026-karcher-web-campaigns/banner-oc-1600x667-01.jpg",
      "/img/projects/2026-karcher-web-campaigns/banner-gif-promo.gif",
      "/img/projects/2026-karcher-web-campaigns/olvida-los-cables.gif",
      "/img/projects/2026-karcher-web-campaigns/banner-home-hg-1900x790-01.jpg",
    ],
    longDescription: "Selección de campañas online desarrolladas durante 2026 para la web de Karcher. Cada mes participo en la gestión de necesidades comerciales, planteamiento visual, diseño de banners, adaptación a formatos web y preparación de piezas promocionales para activaciones como rebajas, Yellow Week, cupones, lanzamientos de gama y campañas estacionales. El trabajo combina criterio de marca, jerarquía comercial y producción ágil para mantener una comunicación constante y coherente en la tienda online.",
    tools: ["Photoshop", "Illustrator"],
  },
  {
    id: "karcher-brand-campaign-built-for-life",
    title: "Karcher Built for Life Campaign",
    year: "2026",
    category: "design",
    tags: ["Karcher", "Campaña de marca", "Vídeo", "Adaptaciones"],
    description: "Campaña de marca previa a verano para Karcher. Diseño, edición de vídeo y adaptación de piezas a formatos digitales y plataformas.",
    images: [
      "/img/projects/2026-karcher-brand-campaign/hpw-c-100.jpg",
      "/img/projects/2026-karcher-brand-campaign/wd-c-100.jpg",
      "/img/projects/2026-karcher-brand-campaign/pv-video-hpw.mp4",
      "/img/projects/2026-karcher-brand-campaign/hpw-9x16.mp4",
    ],
    longDescription: "Campaña de marca desarrollada en los meses previos a verano para Karcher, centrada en la línea Built for Life y en gamas clave como HPW y WD. Me encargué de crear los diseños principales, preparar las piezas visuales y adaptar los vídeos a los formatos necesarios para distintos soportes y plataformas como Amazon Prime, Netflix, Movistar, DAZN, entre otras. El proyecto combina dirección gráfica, adaptación de formatos y edición de vídeo para mantener coherencia de marca en una campaña multicanal.",
    tools: ["Photoshop", "Illustrator", "Premiere Pro"],
  },
  {
    id: "karcher-retail-print-materials",
    title: "Karcher Retail & Print Materials",
    year: "2026",
    category: "design",
    tags: ["Karcher", "Retail", "Impresión", "Trade marketing"],
    description: "Materiales retail e impresos para Karcher Centers, ferreterías y eventos. Diseño, composición y preparación final para imprenta.",
    images: [
      "/img/projects/2026-karcher-retail-print/karcher-center-valencia-vinilo.jpeg",
      "/img/projects/2026-karcher-retail-print/mesa-de-trabajo-2-100.jpg",
      "/img/projects/2026-karcher-retail-print/vinilo-valencia.jpg",
      "/img/projects/2026-karcher-retail-print/cabecera-expositor-oc-handheld.jpg",
      "/img/projects/2026-karcher-retail-print/cabecera-expositor-rcw-2-negro.jpg",
      "/img/projects/2026-karcher-retail-print/oc-handled.jpg",
      "/img/projects/2026-karcher-retail-print/hoja-vendedora-fcv-4-dry.jpg",
      "/img/projects/2026-karcher-retail-print/hoja-vendedora-rcw-2-extra.jpg",
      "/img/projects/2026-karcher-retail-print/calefaccion-hogar-cliente-coferdroza.jpg",
      "/img/projects/2026-karcher-retail-print/renobat-galicia-01.jpg",
      "/img/projects/2026-karcher-retail-print/revista-kira-01.jpg",
      "/img/projects/2026-karcher-retail-print/synergas-2026-a4.jpg",
      "/img/projects/2026-karcher-retail-print/trade-bike.jpg",
      "/img/projects/2026-karcher-retail-print/trade-bike-2.jpg",
    ],
    longDescription: "Conjunto de materiales de retail e impresión desarrollados para Karcher Centers, ferreterías, distribuidores y eventos. El trabajo incluye diseño gráfico, composición de piezas comerciales, adaptación a soportes físicos, vinilos, cabeceras de expositor, hojas vendedoras, materiales de trade marketing y preparación de artes finales para imprenta. Cada pieza se plantea para mantener coherencia de marca, claridad comercial y viabilidad técnica en producción.",
    tools: ["Illustrator", "Photoshop", "InDesign", "Arte final"],
  },

  // ===== 2023 =====
  {
    id: "ntrsv-visual-identity",
    title: "NTRSV Visual Identity",
    year: "2023",
    category: "branding",
    tags: ["Identidad visual", "Branding", "Corporativo"],
    description: "Identidad visual completa para NTRSV. Desarrollo de marca, aplicación en soportes y guía de estilo.",
    images: [
      "/img/projects/2023-ntrsv-visual-identity/1_ciwqcm.png",
      "/img/projects/2023-ntrsv-visual-identity/2_lxmj5y.png",
      "/img/projects/2023-ntrsv-visual-identity/3_amhwdg.png",
      "/img/projects/2023-ntrsv-visual-identity/4_osf97o.png",
      "/img/projects/2023-ntrsv-visual-identity/5_ru0jus.png",
      "/img/projects/2023-ntrsv-visual-identity/6_e7qref.png",
      "/img/projects/2023-ntrsv-visual-identity/7_exvz2w.png",
      "/img/projects/2023-ntrsv-visual-identity/8_ezae5f.png",
      "/img/projects/2023-ntrsv-visual-identity/9_ajqkfd.png",
      "/img/projects/2023-ntrsv-visual-identity/10_kdodvm.png",
      "/img/projects/2023-ntrsv-visual-identity/11_hdiox3.png",
      "/img/projects/2023-ntrsv-visual-identity/12_weu6wn.png",
      "/img/projects/2023-ntrsv-visual-identity/13_dwia9h.png",
      "/img/projects/2023-ntrsv-visual-identity/14_vlnbk7.png",
      "/img/projects/2023-ntrsv-visual-identity/17_axn9g0.png",
    ],
    longDescription: "Proyecto completo de identidad visual para NTRSV, abarcando desde el concepto inicial hasta la aplicación en múltiples soportes. Se desarrolló un sistema visual coherente con paleta cromática, tipografía corporativa y aplicaciones en papelería, digital y señalética.",
    tools: ["Illustrator", "Photoshop", "InDesign"],
  },
  {
    id: "xomega-visual-identity",
    title: "Xomega Visual Identity",
    year: "2023",
    category: "branding",
    tags: ["Identidad visual", "Branding", "Corporativo"],
    description: "Identidad visual y aplicaciones de marca para Xomega. Sistema de diseño modular.",
    images: [
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_azl0ov.png",
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_1_ow1xu4.png",
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_2_zlwfa8.png",
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_3_o1lnhc.png",
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_4_qlffh6.png",
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_6_lrrchm.png",
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_7_acj7vy.png",
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_8_fyhuvy.png",
      "/img/projects/2023-xomega-visual-identity/Mesa_de_trabajo_1_11_nvgf8o.png",
    ],
    longDescription: "Sistema de identidad visual para Xomega basado en un enfoque modular. Se diseñó un logotipo principal, variantes, paleta de color, tipografía y un conjunto de aplicaciones que garantizan la coherencia de la marca en todos los touchpoints.",
    tools: ["Illustrator", "Photoshop", "InDesign"],
  },
  {
    id: "mitsuo-jkatsui-editorial",
    title: "Mitsuo Katsui — Editorial (-libro)",
    year: "2023",
    category: "editorial",
    tags: ["Editorial", "Libro", "Maquetación"],
    description: "Libro editorial sobre Mitsuo Katsui. Maquetación, retícula y tratamiento visual completo.",
    images: [
      "/img/projects/2023-mitsuo-jkatsui-editorial-libro/1_1_xjmx8r.png",
      "/img/projects/2023-mitsuo-jkatsui-editorial-libro/2_ffc9zv.png",
      "/img/projects/2023-mitsuo-jkatsui-editorial-libro/3_ddoesf.png",
      "/img/projects/2023-mitsuo-jkatsui-editorial-libro/4_vdq0l5.png",
      "/img/projects/2023-mitsuo-jkatsui-editorial-libro/5_hiowp5.png",
    ],
    hasBookAnimation: true,
    longDescription: "Maquetación editorial del libro sobre el diseñador japonés Mitsuo Katsui. Se trabajó una retícula cuidada, tratamiento tipográfico riguroso y un sistema visual que respeta la estética del autor mientras aporta una narrativa editorial contemporánea.",
    tools: ["InDesign", "Photoshop", "Illustrator"],
  },
  {
    id: "cruz-cafune-concert",
    title: "Cruz Cafuné — Concierto",
    year: "2023",
    category: "poster",
    tags: ["Cartel", "Concierto", "Música"],
    description: "Cartelería para concierto de Cruz Cafuné. Diseño promocional y aplicación digital.",
    images: [
      "/img/projects/2023-cruz-cafune-concert-poster/cruzi_it80kv.jpg",
      "/img/projects/2023-cruz-cafune-concert-poster/2_syalb6.png",
    ],
    longDescription: "Diseño de cartelería para concierto de Cruz Cafuné. Se desarrolló una pieza gráfica impactante para promoción en formato físico y digital, manteniendo la identidad del artista.",
    tools: ["Photoshop", "Illustrator"],
  },
  {
    id: "nike-sneaker-poster",
    title: "Nike Sneaker Poster",
    year: "2023",
    category: "poster",
    tags: ["Cartel", "Nike", "Moda"],
    description: "Póster conceptual de zapatilla Nike. Composición gráfica y tratamiento de imagen.",
    images: [
      "/img/projects/2023-nike-sneaker-poster/1_m3fws7.png",
      "/img/projects/2023-nike-sneaker-poster/4_d2l3re.png",
      "/img/projects/2023-nike-sneaker-poster/5_cn72jp.png",
      "/img/projects/2023-nike-sneaker-poster/7_sdghef.png",
    ],
    longDescription: "Póster conceptual para Nike. Composición gráfica que combina tipografía, imagen de producto y tratamiento visual contemporáneo para generar una pieza publicitaria de alto impacto.",
    tools: ["Photoshop", "Illustrator"],
  },

  // ===== 2022 =====
  {
    id: "dadaist-vynil",
    title: "Dadaist Vynil",
    year: "2022",
    category: "design",
    tags: ["Vinilo", "Diseño gráfico", "Packaging"],
    description: "Diseño de vinilo conceptual con inspiración dadaísta. Mockups y aplicación gráfica.",
    images: [
      "/img/projects/2022-dadaist-vynil/Dadaismo_cakbco.png",
      "/img/projects/2022-dadaist-vynil/Mockups_dada_ugnwsi.png",
    ],
    longDescription: "Proyecto de diseño de vinilo con estética dadaísta. Se trabajó la composición tipográfica, el collage digital y la aplicación en mockups realistas para presentar el resultado final.",
    tools: ["Illustrator", "Photoshop"],
  },
  {
    id: "tecnocon-visual-identity",
    title: "Tecnocon Visual Identity",
    year: "2022",
    category: "branding",
    tags: ["Identidad visual", "Evento", "Congreso"],
    description: "Identidad visual para Tecnocon. Diseño de marca, aplicaciones y materiales promocionales.",
    images: [
      "/img/projects/2022-tecnocon-visual-identity/Mesa_de_trabajo_11_wbzakk.png",
      "/img/projects/2022-tecnocon-visual-identity/Mesa_de_trabajo_11_2_bodxea.png",
      "/img/projects/2022-tecnocon-visual-identity/Mesa_de_trabajo_11_3_ivrrpb.png",
      "/img/projects/2022-tecnocon-visual-identity/Mesa_de_trabajo_17_2_jw78kp.png",
      "/img/projects/2022-tecnocon-visual-identity/Mesa_de_trabajo_17_3_tg9q6j.png",
      "/img/projects/2022-tecnocon-visual-identity/Mesa_de_trabajo_17_4_s7imkq.png",
      "/img/projects/2022-tecnocon-visual-identity/Mesa_de_trabajo_17_5_zijvud.png",
      "/img/projects/2022-tecnocon-visual-identity/Mesa_de_trabajo_17_6_sntlfg.png",
    ],
    longDescription: "Identidad visual completa para el congreso Tecnocon. Incluye diseño de logotipo, paleta cromática, aplicaciones en merchandising, cartelería, programas de mano y materiales digitales para redes sociales.",
    tools: ["Illustrator", "Photoshop", "InDesign"],
  },
  {
    id: "wedding-design",
    title: "Diseño de Boda",
    year: "2022",
    category: "design",
    tags: ["Boda", "Editorial", "Papelería"],
    description: "Diseño editorial y papelería para evento nupcial. Invitaciones, programas y menús.",
    images: [
      "/img/projects/2022-wedding-design/presentacion_1_1_tzugbz.png",
      "/img/projects/2022-wedding-design/3_mcgrtn.png",
      "/img/projects/2022-wedding-design/4_cxskge.png",
      "/img/projects/2022-wedding-design/ultima_bien_grande_mzoolx.jpg",
    ],
    longDescription: "Conjunto completo de papelería nupcial: invitaciones, programas de ceremonia, menús y detalles. Se trabajó una línea gráfica elegante y coherente con la temática del evento.",
    tools: ["Illustrator", "Photoshop", "InDesign"],
  },
];
